name: net_sniffer shell checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check syntax script
        id: syntax_checker
        run: |
          bash -n sh_tool/bin/net_dumper.sh && script_1=0 || script_1=1
          bash -n sh_tool/bin/net_ipsniffer.sh && script_2=0 || script_2=1
          bash -n sh_tool/bin/net_params.sh && script_3=0 || script_3=1
          [[ $script_1 -eq 0 && $script_2 -eq 0 && $script_3 -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check size script
        id: size_checker
        run: |
          echo Checking size
          code_line_number_1=$(wc -l < sh_tool/bin/net_dumper.sh)
          code_line_number_2=$(wc -l < sh_tool/bin/net_ipsniffer.sh)
          code_line_number_3=$(wc -l < sh_tool/bin/net_params.sh)
          [[ $code_line_number_1 -gt 300 || $code_line_number_2 -gt 300 || $code_line_number_3 -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check on failures
        if: steps.syntax_checker.outputs.status == 'failure' || steps.size_checker.outputs.status == 'failure'
        run: exit 1
